export { default as AddVehicle } from './AddVehicle.vue'
export { default as AddBrandDialog } from './AddBrandDialog.vue'
export { default as BrandSelectPopover } from './BrandSelectPopover.vue'
export { default as ImageDropzone } from './ImageDropzone.vue'
export { default as ListVehicle } from './ListVehicle.vue'
export { default as VehicleCard } from './VehicleCard.vue'
export { default as VehiclesDetails } from './VehicleDetails.vue'
export { default as DeleteDialog } from './DeleteDialog.vue'
export { default } from './AddVehicle.vue'
